### ISSUE TITLE
Only for MRI ruby? Doesnt work with Jruby

### ISSUE THREAD

**Issue by aditya-sanghi** [diogob/postgres-copy#38] opened 2017-02-18 12:14 UTC
find_executable: checking for pg_config... -------------------- yes

--------------------

" -o conftest -I/include/universal-java1.8 -I/usr/local/Cellar/rbenv/1.1.0/versions/jruby-9.1.6.0/lib/ruby/include/ruby/backward -I/usr/local/Cellar/rbenv/1.1.0/versions/jruby-9.1.6.0/lib/ruby/include -I. -I/usr/local/Cellar/postgresql/9.6.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE     -fPIC -DTARGET_RT_MAC_CFM=0  -fno-omit-frame-pointer -fno-strict-aliasing  -fexceptions  conftest.c  -L. -L/usr/local/Cellar/rbenv/1.1.0/versions/jruby-9.1.6.0/lib -L/usr/local/lib    -arch x86_64      "
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <ruby.h>
4: int main(int argc, char **argv)
5: {
6:   return 0;
7: }
/* end */

**Comment by diogob** [comment] 2017-02-23 03:49
Closing as duplicate of #15 
I'll reopen that issue as a possible enhancement.

**Closed by diogob** 2017-02-23 03:49 UTC
